using System.Text;
using OpenRA.Converter.Core.Models.CodeStructure;

namespace OpenRA.Converter.Infrastructure.Services
{
    public interface ICodeWriter
    {
        string WriteClass(CsClass csClass);
    }

    public class CSharpCodeWriter : ICodeWriter
    {
        public string WriteClass(CsClass csClass)
        {
            var sb = new StringBuilder();

            // 1. Header & Usings
            sb.AppendLine("// <auto-generated> This file was generated by the OpenRA Converter. </auto-generated>");
            foreach (var u in csClass.Usings)
            {
                sb.AppendLine($"using {u};");
            }
            sb.AppendLine();

            // 2. Namespace
            sb.AppendLine($"namespace {csClass.Namespace}");
            sb.AppendLine("{");

            // 3. Info Class (Configuration) - usually nested or adjacent
            if (csClass.PairedInfoClass != null)
            {
                WriteClassDefinition(sb, csClass.PairedInfoClass, 1);
                sb.AppendLine();
            }

            // 4. Main Logic Class
            WriteClassDefinition(sb, csClass, 1);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private void WriteClassDefinition(StringBuilder sb, CsClass csClass, int indentLevel)
        {
            string indent = new string('\t', indentLevel);
            string innerIndent = new string('\t', indentLevel + 1);

            // Class Signature
            string inheritance = string.IsNullOrEmpty(csClass.Inherits) ? "" : $" : {csClass.Inherits}";
            if (csClass.Interfaces.Count > 0)
            {
                inheritance += string.IsNullOrEmpty(inheritance) ? " : " : ", ";
                inheritance += string.Join(", ", csClass.Interfaces);
            }

            sb.AppendLine($"{indent}public class {csClass.Name}{inheritance}");
            sb.AppendLine($"{indent}{{");

            // Fields
            foreach (var field in csClass.Fields)
            {
                if (!string.IsNullOrEmpty(field.Description))
                {
                    sb.AppendLine($"{innerIndent}/// <summary>{field.Description}</summary>");
                }

                string access = field.AccessModifier.ToLower();
                string ro = field.IsReadonly ? "readonly " : "";
                string stat = field.IsStatic ? "static " : "";
                string init = field.InitialValue != null ? $" = {field.InitialValue}" : "";

                sb.AppendLine($"{innerIndent}{access} {stat}{ro}{field.Type} {field.Name}{init};");
            }

            if (csClass.Fields.Count > 0) sb.AppendLine();

            // Methods
            foreach (var method in csClass.Methods)
            {
                sb.AppendLine($"{innerIndent}{method.GetSignature()}");
                sb.AppendLine($"{innerIndent}{{");
                foreach (var line in method.BodyLines)
                {
                    sb.AppendLine($"{innerIndent}\t{line}");
                }
                sb.AppendLine($"{innerIndent}}}");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}}}");
        }
    }
}